version: '3'

services:
  app:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    ports:
      - 8000:8000
    restart: unless-stopped
    depends_on:
      - redis
    env_file:
      - ../.env
    networks:
      - backend

  redis:
    image: redis:alpine
    restart: unless-stopped
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - backend

networks:
  backend: